name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --output ./webapp

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ./webapp

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: webapp
        path: ./webapp

    - name: Deploy web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: GitHubApp-45660524
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./webapp
